# Generated by Django 4.0.3 on 2022-04-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comments_posts_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='comment',
            field=models.ManyToManyField(null=True, to='main.comments'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='creation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
