# Generated by Django 4.0.3 on 2022-04-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_posts_comment_alter_posts_creation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comment',
        ),
        migrations.AddField(
            model_name='comments',
            name='news_title',
            field=models.ManyToManyField(to='main.posts'),
        ),
    ]
