# Generated by Django 4.0.3 on 2022-04-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_posts_comment_comments_news_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='news_title',
        ),
        migrations.AddField(
            model_name='posts',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='main.comments'),
        ),
    ]
