# Generated by Django 4.0.3 on 2022-04-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_comments_news_title_posts_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='comment',
        ),
    ]
