# Generated by Django 4.0.3 on 2022-04-06 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_posts_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
