# Generated by Django 4.0.3 on 2022-04-27 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_comments_name_comments_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='name',
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.ManyToManyField(related_name='title_post', to='main.posts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
