# Generated by Django 4.0.3 on 2022-04-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_comments_create_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
