# Generated by Django 4.0.3 on 2022-04-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_posts_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='likes',
            field=models.CharField(blank=True, default='0', max_length=255, null=True),
        ),
    ]
