# Generated by Django 4.0.3 on 2022-04-28 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_posts_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='likes',
        ),
    ]
